services:
  - type: web
    name: dwrks_test
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node dist/src/app.js
    envVars:
      - key: NODE_ENV
        value: production